name: EasyRecipes
version: '${project.version}'
main: net.yellowmedia.easyrecipes.EasyRecipes
api-version: 1.18
authors: [ Yellow571 ]
description: Allows for the creation of both vanilla items and special plugin-created items

commands:
  easyrecipes:
    description: Master command for EasyRecipes
    usage: /easyrecipes
    aliases: [er]
    default: op