name: EasyRecipes
version: '${project.version}'
main: net.yellowmedia.easyrecipes.EasyRecipes
api-version: 1.18
authors: [ Yellow571 ]
description: Allows for the creation of both vanilla items and special plugin-created items

commands:
  easyrecipes:
    description: Master command for EasyRecipes
    usage: /easyrecipes
    aliases: [er]
    default: op

permissions:
  easyrecipes.*:
    description: Wildcard permission for EasyRecipes
    default: op
    children:
      easyrecipes.create: true
      easyrecipes.delete: true
      easyrecipes.list: true
      easyrecipes.craft.*: true
  easyrecipes.create:
    description: Allows for the creation of custom recipes
    default: op
  easyrecipes.delete:
    description: Allows for the deletion of custom recipes
    default: op
  easyrecipes.list:
    description: Allows for current custom recipes to be viewed
    default: op
  easyrecipes.craft.*:
    description: Wildcard permission allowing for the crafting of all created recipes
    default: true