name: EasyRecipes
version: '1.0'
main: net.yellowmedia.easyrecipes.EasyRecipes
api-version: 1.18
authors: [ Yellow571 ]
description: Allows for the creation of both vanilla items and special plugin-created items

commands:
  createrecipe:
    description: Creates a custom recipe
    usage: /createrecipe
    default: op